FROM python:3.14-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
# Chạy trực tiếp file app.py để Flask nhận diện debug mode
CMD ["python", "app.py"]